spring.application.name=application
server.port=8089


spring.datasource.url=jdbc:mariadb://192.168.0.103:3306/Eos
spring.datasource.username=wiezon
spring.datasource.password=wiezon1!

spring.jpa.hibernate.ddl-auto=create


server.url=localhost:9999
server.apiKey=test

spring.main.web-application-type=none


# Test
#FULL/PAY
base.datetime=20260310
test.mode=FULL
mid=wytest
gid=wzon00001g
l1_vid=wzon00001a

#crct info
crct.ptnCd=DOZN9
crct.cpid=NPIER9
crct.keyType=01
crct.key=3829e78f-bb76-419f-a2a9-516435d231f8


#pay
pay.count=100
pay.ptnCd=01
pay.mid=wytest001m
pay.gid=wzon00001g
pay.vid=wzon00001a

#cpid info
##################### galaxia #####################
#cpids[0].cert.ptnCd=13
#cpids[0].cert.cpid=cert_galaxy_0
#cpids[0].cert.keyType=01
#cpids[0].cert.key=/home/payq/bld/cardPg/galaxia/config/config.ini
##???
#cpids[0].old.cert.ptnCd=13
#cpids[0].old.cert.cpid=old_cert_galaxy_0
#cpids[0].old.cert.keyType=01
#cpids[0].old.cert.key=/home/payq/bld/cardPg/galaxia/config/config.ini
##????
#cpids[0].offline.ptnCd=13
#cpids[0].offline.cpid=offline_galaxy_0
#cpids[0].offline.keyType=01
#cpids[0].offline.key=/home/payq/bld/cardPg/galaxia/config/config.ini
##???
#cpids[0].no.cert.ptnCd=13
#cpids[0].no.cert.cpid=no_cert_galaxy_0
#cpids[0].no.cert.keyType=01
#cpids[0].no.cert.key=/home/payq/bld/cardPg/galaxia/config/config.ini
######################################################


##################### nicepay #####################
cpids[0].cert.ptnCd=04
cpids[0].cert.cpid=cert_nice_0
cpids[0].cert.keyType=02
cpids[0].cert.key=EYzu8jGGMfqaDEp76gSckuvnaHHu+bC4opsSN6lHv3b2lurNYkVXrZ7Z1AoqQnXI3eLuaUFyoRNC6FkrzVjceg==
#???
cpids[0].old.cert.ptnCd=04
cpids[0].old.cert.cpid=old_cert_nice_0
cpids[0].old.cert.keyType=02
cpids[0].old.cert.key=b+zhZ4yOZ7FsH8pm5lhDfHZEb79tIwnjsdA0FBXh86yLc6BJeFVrZFXhAoJ3gEWgrWwN+lJMV0W4hvDdbe4Sjw==
#????
cpids[0].offline.ptnCd=04
cpids[0].offline.cpid=offline_nice_0
cpids[0].offline.keyType=02
cpids[0].offline.key=
#???
cpids[0].no.cert.ptnCd=04
cpids[0].no.cert.cpid=no_cert_nice_0
cpids[0].no.cert.keyType=02
cpids[0].no.cert.key=aW8ykH2s1xLHvKVctt+gQFsHJPt34fc2pLuJYKWc6E7VYy7A82jRkG6RpamERy8oImjOjRYmesMkWbJ9SS5bEw==
######################################################